=== pepsimanpa/mcmc2/ProtocolXml/XSD/CommonBindingSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://lignex1.com/mcmc2/umsSchema"
           xmlns="http://lignex1.com/mcmc2/umsSchema"
           elementFormDefault="qualified">

    <xs:element name="SensorBinding" type="BindingCompositionType"/>
    <xs:element name="PlatformBinding" type="BindingCompositionType"/>
    <xs:element name="PayloadBinding" type="BindingCompositionType"/>
    <xs:element name="CommBinding" type="BindingCompositionType"/>

    <xs:complexType name="BindingCompositionType">
        <xs:sequence>
            <xs:element name="Monitors" type="MonitorsType" minOccurs="0"/>
            <xs:element name="Controls" type="ControlsType" minOccurs="0"/>
            <xs:element name="SensorProducts" type="SensorProductsType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MonitorsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="MonitorBindingDDS" type="MonitorBindingDDSType"/>
            <xs:element name="MonitorBinding" type="MonitorBindingType"/>
        </xs:choice>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ControlsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ControlBindingDDS" type="ControlBindingDDSType"/>
            <xs:element name="ControlBinding" type="ControlBindingType"/>
        </xs:choice>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SensorProductsType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ProductBinding" type="ProductBindingType"/>
        </xs:choice>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ChannelType">
        <xs:attribute name="topicName" type="xs:string" use="required"/>
        <xs:attribute name="typeName" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="DDSChannelType">
        <xs:attribute name="topicName" type="xs:string" use="required"/>
        <xs:attribute name="typeName" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="MessageChannelType">
        <xs:attribute name="infoCode" type="xs:unsignedShort"/>
        <xs:attribute name="messageType" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="RTPChannelType"/>

    <xs:group name="ProtocolChannelChoice">
        <xs:choice>
            <xs:element name="DDSChannel" type="DDSChannelType"/>
            <xs:element name="TCPChannel" type="MessageChannelType"/>
            <xs:element name="UDPChannel" type="MessageChannelType"/>
            <xs:element name="RS422Channel" type="MessageChannelType"/>
            <xs:element name="RTPChannel" type="RTPChannelType"/>
        </xs:choice>
    </xs:group>

    <!-- Declarative wire representation. New Binding XML should prefer these over converter identifiers. -->
    <xs:simpleType name="WireDataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="UInt8"/>
            <xs:enumeration value="Int8"/>
            <xs:enumeration value="UInt16"/>
            <xs:enumeration value="Int16"/>
            <xs:enumeration value="UInt32"/>
            <xs:enumeration value="Int32"/>
            <xs:enumeration value="UInt64"/>
            <xs:enumeration value="Int64"/>
            <xs:enumeration value="Float32"/>
            <xs:enumeration value="Float64"/>
            <xs:enumeration value="Boolean"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ValueMapEntryType">
        <xs:attribute name="cdm" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ValueMapType">
        <xs:sequence>
            <xs:element name="Map" type="ValueMapEntryType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Declarative mapping from a prepared sourceField scalar value to a wire value. -->
    <xs:complexType name="SourceValueMapEntryType">
        <xs:attribute name="sourceValue" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SourceValueMapType">
        <xs:sequence>
            <xs:element name="Map" type="SourceValueMapEntryType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SemanticSetType">
        <xs:attribute name="cdm" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SemanticBindType">
        <xs:attribute name="cdm" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="SentinelType">
        <xs:sequence>
            <xs:element name="Set" type="SemanticSetType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="NormalBindingType">
        <xs:sequence>
            <xs:element name="Set" type="SemanticSetType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Bind" type="SemanticBindType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Legacy extension point retained only so existing AUV/USV XML remains valid during migration. -->
    <xs:complexType name="DerivedSemanticType">
        <xs:attribute name="cdm" type="xs:string" use="required"/>
        <xs:attribute name="converter" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="FieldType">
        <xs:sequence>
            <xs:element name="ValueMap" type="ValueMapType" minOccurs="0"/>
            <xs:element name="Sentinel" type="SentinelType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Normal" type="NormalBindingType" minOccurs="0"/>
            <xs:element name="DerivedSemantic" type="DerivedSemanticType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="dataType" type="WireDataType"/>
        <xs:attribute name="scale" type="xs:decimal"/>
        <xs:attribute name="length" type="xs:positiveInteger"/>
        <xs:attribute name="format" type="xs:string"/>
        <xs:attribute name="inputUnit" type="xs:string"/>
        <xs:attribute name="outputUnit" type="xs:string"/>
        <xs:attribute name="converter" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="FixedFieldType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="dataType" type="WireDataType"/>
        <xs:attribute name="length" type="xs:positiveInteger"/>
        <xs:attribute name="format" type="xs:string"/>
        <xs:attribute name="converter" type="xs:string"/>
    </xs:complexType>

    <!-- OM prepares sourceField values. Binding only maps prepared values to wire representation. -->
    <xs:complexType name="DerivedFieldType">
        <xs:sequence>
            <xs:element name="ValueMap" type="ValueMapType" minOccurs="0"/>
            <xs:element name="SourceValueMap" type="SourceValueMapType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="sourceField" type="xs:string" use="required"/>
        <xs:attribute name="dataType" type="WireDataType"/>
        <xs:attribute name="scale" type="xs:decimal"/>
        <xs:attribute name="length" type="xs:positiveInteger"/>
        <xs:attribute name="format" type="xs:string"/>
        <xs:attribute name="converter" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="ByteOrderType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="little"/>
            <xs:enumeration value="big"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="BitMemberType">
        <xs:sequence>
            <xs:element name="ValueMap" type="ValueMapType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="sourceField" type="xs:string"/>
        <xs:attribute name="offset" type="xs:nonNegativeInteger" use="required"/>
        <xs:attribute name="width" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="fixedValue" type="xs:string"/>
        <xs:attribute name="converter" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="PackedFieldType">
        <xs:sequence>
            <xs:element name="BitMember" type="BitMemberType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="width" type="xs:positiveInteger" use="required"/>
        <!-- byteOrder is legacy override; new files inherit system/specification DataEncoding. -->
        <xs:attribute name="byteOrder" type="ByteOrderType"/>
        <xs:attribute name="defaultValue" type="xs:string" default="0"/>
        <xs:attribute name="expectedValue" type="xs:string"/>
        <xs:attribute name="expectedMask" type="xs:string"/>
        <xs:attribute name="converter" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ElementType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Field" type="FieldType"/>
            <xs:element name="FixedField" type="FixedFieldType"/>
            <xs:element name="DerivedField" type="DerivedFieldType"/>
            <xs:element name="PackedField" type="PackedFieldType"/>
            <xs:element name="ArrayField" type="ArrayFieldType"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ArrayFieldType">
        <xs:sequence>
            <xs:element name="Element" type="ElementType"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="cdm" type="xs:string"/>
        <xs:attribute name="minOccurs" type="xs:nonNegativeInteger"/>
        <xs:attribute name="maxOccurs" type="xs:string"/>
    </xs:complexType>

    <xs:group name="BindingFieldChoice">
        <xs:choice>
            <xs:element name="Field" type="FieldType"/>
            <xs:element name="FixedField" type="FixedFieldType"/>
            <xs:element name="DerivedField" type="DerivedFieldType"/>
            <xs:element name="PackedField" type="PackedFieldType"/>
            <xs:element name="ArrayField" type="ArrayFieldType"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="MatchFieldType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="mask" type="xs:string" use="optional"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ProductBindingType">
        <xs:sequence>
            <xs:group ref="ProtocolChannelChoice"/>
            <xs:element name="MatchField" type="MatchFieldType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="MonitorBindingDDSType">
        <xs:sequence>
            <xs:element name="Channel" type="ChannelType"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ReplyBindingType">
        <xs:sequence>
            <xs:element name="Channel" type="ChannelType"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="timeout" type="xs:decimal"/>
    </xs:complexType>

    <xs:complexType name="ControlBindingDDSType">
        <xs:sequence>
            <xs:element name="Channel" type="ChannelType"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
            <xs:element name="ReplyBinding" type="ReplyBindingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="MonitorBindingType">
        <xs:sequence>
            <xs:group ref="ProtocolChannelChoice"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ProtocolReplyBindingType">
        <xs:sequence>
            <xs:group ref="ProtocolChannelChoice"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="timeout" type="xs:decimal"/>
    </xs:complexType>

    <xs:complexType name="ControlBindingType">
        <xs:sequence>
            <xs:group ref="ProtocolChannelChoice"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice>
            <xs:element name="ReplyBinding" type="ProtocolReplyBindingType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="semantic_id" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== pepsimanpa/mcmc2/ProtocolXml/USV/Lidar/LidarBinding.xml
<?xml version='1.0' encoding='UTF-8'?>
<SensorBinding xmlns="http://lignex1.com/mcmc2/umsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ../../XSD/CommonBindingSchema.xsd">
  <!--라이다 정보처리장치 Binding: 라이다 정보처리 CSC 및 원격통제장치 CSCI 직접 연동 기준-->
  <!--공용 식별자 규칙: SurfaceDetection=0x03, LidarProcessorCard=0x02. 두 값만으로 장비가 식별되고 별도 세부 장비 ID가 정의되어 있지 않으므로 dstSubEquipmentID는 미사용값 0x00을 적용한다.-->
  <Monitors semantic_id="monitor">
    <MonitorBinding semantic_id="lidarContacts">
      <DDSChannel topicName="RUSV::SA::CIPE::LidarContactReportType" typeName="LidarContactReportType"/>
      <Field name="usvHeader"/>
      <Field name="contactNum" cdm="Contact.Lidar.Count" dataType="Int32"/>
      <ArrayField name="lidarDetectionSeq" cdm="Contact.Lidar.List" minOccurs="0" maxOccurs="256">
        <Element name="contact" cdm="Contact.Lidar.Item">
          <Field name="id" cdm="Contact.Identifier" dataType="UInt32"/>
          <Field name="boxHeight" cdm="Contact.Lidar.Dimension.Height" dataType="Float64"/>
          <Field name="boxWidth" cdm="Contact.Lidar.Dimension.Width" dataType="Float64"/>
          <Field name="boxLength" cdm="Contact.Lidar.Dimension.Length" dataType="Float64"/>
          <Field name="relativePositionX" cdm="Contact.Lidar.RelativePosition.X" dataType="Float64"/>
          <Field name="relativePositionY" cdm="Contact.Lidar.RelativePosition.Y" dataType="Float64"/>
          <Field name="relativePositionZ" cdm="Contact.Lidar.RelativePosition.Z" dataType="Float64"/>
          <Field name="relativeAzimuth" cdm="Contact.Lidar.Bearing.RelativeAzimuth" dataType="Float64"/>
        </Element>
      </ArrayField>
    </MonitorBinding>

    <MonitorBinding semantic_id="cipeCbitStatus">
      <DDSChannel topicName="RUSV::SO::CIPE::CIPECBITReportType" typeName="CIPECBITReportType"/>
      <Field name="usvHeader"/>
      <Field name="cipeCBITStatus.cipeOperationalStatus" cdm="Health.CIPE.EquipmentLink" dataType="UInt8">
        <ValueMap><Map cdm="Health.CIPE.Lidar.Connected" value="20"/><Map cdm="Health.CIPE.Lidar.Disconnected" value="23"/></ValueMap>
      </Field>
      <Field name="cipeCBITStatus.operationalStatus" cdm="Health.CIPE.OperationalStatus" dataType="UInt8">
      <ValueMap><Map cdm="Health.Normal" value="0"/><Map cdm="Health.Degraded" value="1"/><Map cdm="Health.Unavailable" value="2"/><Map cdm="Health.NoResponse" value="3"/></ValueMap>
    </Field>
    </MonitorBinding>
  </Monitors>

  <Controls semantic_id="control">
    <ControlBinding semantic_id="startIntegration">
      <DDSChannel topicName="RUSV::C2::RCU::IntegrationControlType" typeName="IntegrationControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <DerivedField name="destination" sourceField="System.Target.Lidar"/>
      <ReplyBinding semantic_id="startIntegrationAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <!--ACK의 목적지 장비 ID는 원 명령 발행자(FRCU/PRCU)에 따라 달라질 수 있으므로 특정 RemoteControl equipmentID로 고정하지 않는다.-->
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
    </ControlBinding>

    <ControlBinding semantic_id="restartSystem">
      <DDSChannel topicName="RUSV::C2::RCU::SystemRebootControlType" typeName="SystemRebootControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <DerivedField name="destination" sourceField="System.Target.Lidar"/>
      <ReplyBinding semantic_id="restartSystemAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
    </ControlBinding>

    <ControlBinding semantic_id="requestIbit">
      <DDSChannel topicName="RUSV::SO::RCU::RCUIBITControlType" typeName="RCUIBITControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <DerivedField name="destination" sourceField="System.Target.Lidar"/>
      <ReplyBinding semantic_id="requestIbitAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
      <ReplyBinding semantic_id="requestIbitResult" required="true">
        <DDSChannel topicName="RUSV::SO::CIPE::CIPEIBITReportType" typeName="CIPEIBITReportType"/>
        <Field name="usvHeader"/>
        <Field name="cipeIBITStatus.cipeOperationalStatus" cdm="Health.CIPE.EquipmentLink" dataType="UInt8">
          <ValueMap><Map cdm="Health.CIPE.Lidar.Connected" value="20"/><Map cdm="Health.CIPE.Lidar.Disconnected" value="23"/></ValueMap>
        </Field>
        <Field name="cipeIBITStatus.operationalStatus" cdm="Health.CIPE.OperationalStatus" dataType="UInt8">
          <ValueMap><Map cdm="Health.Normal" value="0"/><Map cdm="Health.Degraded" value="1"/><Map cdm="Health.Unavailable" value="2"/><Map cdm="Health.NoResponse" value="3"/></ValueMap>
        </Field>
        <!--DDS에는 CPU 상태 enum이 별도로 존재하지 않으며 실제 cpuTemperature 값만 전달된다. 원본 온도 판정 기준(정상 30~85, 성능저하 ~29 또는 86~89, 위험 90~)은 구현/HMI 판단 기준으로 사용한다.-->
        <Field name="cipeIBITStatus.cipeProcessorIBIT.cpuTemperature" cdm="Health.CIPE.Processor.CpuTemperature" dataType="Float64"/>
        <Field name="cipeIBITStatus.cipeProcessorIBIT.cpuLoad" cdm="Health.CIPE.Processor.CpuLoad" dataType="Float64"/>
      </ReplyBinding>
    </ControlBinding>

    <ControlBinding semantic_id="requestPbit">
      <DDSChannel topicName="RUSV::SO::RCU::RCUPBITControlType" typeName="RCUPBITControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <DerivedField name="destination" sourceField="System.Target.Lidar"/>
      <ReplyBinding semantic_id="requestPbitAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
      <ReplyBinding semantic_id="requestPbitResult" required="true">
        <DDSChannel topicName="RUSV::SO::CIPE::CIPEPBITReportType" typeName="CIPEPBITReportType"/>
        <Field name="usvHeader"/>
        <Field name="cipePBITStatus.cipeOperationalStatus" cdm="Health.CIPE.EquipmentLink" dataType="UInt8">
          <ValueMap><Map cdm="Health.CIPE.Lidar.Connected" value="20"/><Map cdm="Health.CIPE.Lidar.Disconnected" value="23"/></ValueMap>
        </Field>
        <Field name="cipePBITStatus.operationalStatus" cdm="Health.CIPE.OperationalStatus" dataType="UInt8">
        <ValueMap><Map cdm="Health.Normal" value="0"/><Map cdm="Health.Degraded" value="1"/><Map cdm="Health.Unavailable" value="2"/><Map cdm="Health.NoResponse" value="3"/></ValueMap>
      </Field>
      </ReplyBinding>
    </ControlBinding>
  </Controls>
</SensorBinding>
