=== pepsimanpa/mcmc2/ProtocolXml/XSD/VehicleSpecificationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://lignex1.com/mcmc2/umsSchema"
    xmlns="http://lignex1.com/mcmc2/umsSchema"
    elementFormDefault="qualified">
    <xs:include schemaLocation="./CommonSpecSchema.xsd" />

    <xs:element name="VehicleSpec" type="VehicleSpecType" />
    
    <xs:complexType name="VehicleSpecType">
        <xs:all>
            <xs:element name="Identification" type="IdentificationType" minOccurs="1" />
            <xs:element name="DataEncoding" type="DataEncodingType" minOccurs="0" />
            <xs:element name="Sensors" type="Sensors" minOccurs="0" maxOccurs="1" />
            <xs:element name="Platform" type="Platform" minOccurs="0" maxOccurs="1" />
            <xs:element name="Payloads" type="Payload" minOccurs="0" maxOccurs="1" />
            <xs:element name="Comms" type="Comms" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="VehicleByteOrderType">
        <xs:restriction base="xs:string"><xs:enumeration value="little"/><xs:enumeration value="big"/></xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DataEncodingType"><xs:attribute name="byteOrder" type="VehicleByteOrderType" use="required"/></xs:complexType>

    <xs:complexType name="IdentificationType">
        <xs:all>
            <xs:element name="ID" type="xs:string" minOccurs="1" />
            <xs:element name="Name" type="xs:string" minOccurs="1" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="Sensors">
        <xs:sequence>
            <xs:element name="SensorSpecRef" type="SensorSpecRefType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Platform">
        <xs:sequence>
            <xs:element name="PlatformSpecRef" type="PlatformSpecRefType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Payload">
        <xs:sequence>
            <xs:element name="PayloadSpecRef" type="PayloadSpecRefType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Comms">
        <xs:sequence>
            <xs:element name="CommSpecRef" type="CommSpecRefType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SensorSpecRefType">
        <xs:sequence>
            <xs:element name="SemanticPath" type="xs:string"/>
            <xs:element name="BindingPath" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="SpecAttrs"/>
    </xs:complexType>

    <xs:complexType name="PlatformSpecRefType">
        <xs:sequence>
            <xs:element name="SemanticPath" type="xs:string"/>
            <xs:element name="BindingPath" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="SpecAttrs"/>
    </xs:complexType>

    <xs:complexType name="PayloadSpecRefType">
        <xs:sequence>
            <xs:element name="SemanticPath" type="xs:string"/>
            <xs:element name="BindingPath" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="SpecAttrs"/>
    </xs:complexType>

    <xs:complexType name="CommSpecRefType">
        <xs:sequence>
            <xs:element name="SemanticPath" type="xs:string"/>
            <xs:element name="BindingPath" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="SpecAttrs"/>
    </xs:complexType>
</xs:schema>

=== pepsimanpa/mcmc2/ProtocolXml/MDV/MdvSpecification.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    MDV 전체 사양 조합 파일.
    MDV 기능과 rov_common.csv의 양방향 TCP 하트비트는
    MdvPlatformSemantic.xml과 MdvTcpBinding.xml에 통합하여 정의한다.
-->
<VehicleSpec xmlns="http://lignex1.com/mcmc2/umsSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ./VehicleSpecificationSchema.xsd">
    <Identification>
        <ID>MCM-MDV-001</ID>
        <Name>MDV</Name>
    </Identification>
    <Platform>
        <!--
            Platform.MDV는 공통 의미 데이터 CDM이 아니라 MDV Profile을 가리키는 잠정 참조 표현이다.
            현재 XSD에 ProfileRef 전용 직렬화가 없어 AUV Specification과 같은 cdm 속성 형식을 유지한다.
        -->
        <PlatformSpecRef id="mdv" name="MDV" cdm="Platform.MDV">
            <SemanticPath>MdvPlatformSemantic.xml</SemanticPath>
            <BindingPath>MdvTcpBinding.xml</BindingPath>
        </PlatformSpecRef>
    </Platform>
</VehicleSpec>

=== pepsimanpa/mcmc2/ProtocolXml/EMDW/EmdwSpecification.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
    EMDW 전체 사양 조합 파일.
    EMDW 기능과 rov_common.csv의 양방향 TCP 하트비트는
    EmdwPlatformSemantic.xml과 EmdwTcpBinding.xml에 통합하여 정의한다.
-->
<VehicleSpec xmlns="http://lignex1.com/mcmc2/umsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ./VehicleSpecificationSchema.xsd">
    <Identification>
        <ID>MCM-EMDW-001</ID>
        <Name>EMDW</Name>
    </Identification>
    <DataEncoding byteOrder="little"/>
    <Platform>
        <!--
            Platform.EMDW는 공통 의미 데이터 CDM이 아니라 EMDW Profile을 가리키는 잠정 참조 표현이다.
            현재 XSD에 ProfileRef 전용 직렬화가 없어 AUV Specification과 같은 cdm 속성 형식을 유지한다.
        -->
        <PlatformSpecRef id="emdw" name="EMDW" cdm="Platform.EMDW">
            <SemanticPath>EmdwPlatformSemantic.xml</SemanticPath>
            <BindingPath>EmdwTcpBinding.xml</BindingPath>
        </PlatformSpecRef>
    </Platform>
</VehicleSpec>

=== pepsimanpa/mcmc2/ProtocolXml/AUV/AuvSpecification.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- 생성일시: 2026-08-04 11:51:54 KST -->
<VehicleSpec xmlns="http://lignex1.com/mcmc2/umsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ./VehicleSpecificationSchema.xsd">
    <Identification>
        <ID>MCM-AUV-001</ID>
        <Name>AUV</Name>
    </Identification>
    <Platform>
        <!--
            CDM 분류상 Platform.AUV는 의미 데이터 CDM이 아니라 AUV Profile 참조이다.
            현재 XSD에 ProfileRef 전용 직렬화가 없어 cdm 속성에는 기존 호환 값을 잠정 유지한다.
        -->
        <PlatformSpecRef id="auv" name="AUV" cdm="Platform.AUV">
            <SemanticPath>AuvPlatformSemantic.xml</SemanticPath>
            <BindingPath>AuvPlatformRfBinding.xml</BindingPath>
            <BindingPath>AuvPlatformUcdBinding.xml</BindingPath>
        </PlatformSpecRef>
    </Platform>
    <Comms>
        <!--
            CDM 분류상 Communication.RF는 RFCommunication Capability 참조이다.
            ProfileRef 직렬화 방식이 확정될 때까지 기존 cdm 속성 표현을 잠정 유지한다.
        -->
        <CommSpecRef id="auvRfCommunication" name="AUV RF 통신장치" cdm="Communication.RF">
            <SemanticPath>AuvRfCommSemantic.xml</SemanticPath>
            <BindingPath>AuvRfCommBinding.xml</BindingPath>
        </CommSpecRef>
    </Comms>
</VehicleSpec>

=== pepsimanpa/mcmc2/ProtocolXml/USV/UsvSpecification.xml
<?xml version='1.0' encoding='UTF-8'?>
<VehicleSpec xmlns="http://lignex1.com/mcmc2/umsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ./VehicleSpecificationSchema.xsd">
  <!--
    USV Vehicle Specification은 USV 원격 운용을 위한 기본적인 사양에 대한 설명을 포함하는 명세서이다.
    USV의 기본적인(필수적인) 운용이 가능한 정도의 사양만을 명세하는 것으로 USV의 모든 정보를 표현하려하지 않는 것이 중요하다.
    USV에서 가져올 정보, 제어할 정보에 집중해서 작성한다.
    작성해야될 Spec의 큰 기준 중 하나는 지휘소에서 원격 운용, 접근이 가능한 장치가 기준이 된다.
    원격 지휘소에서 제어할 수 있는 항목 혹은 원격 지휘소에서 획득해야하는 정보 중심으로 작성하는 것이 중요하다.
    -->
  <!--
    
    -->
  <Identification>
    <ID>MCM-USV-LIG-001</ID>
    <Name>M-Hunter</Name>
  </Identification>
  <!-- 센서 장비 -->
  <Sensors>
    <SensorSpecRef id="sideScanSonar" name="예인형수중탐색장치">
      <SemanticPath>SideScanSonarSemantic.xml</SemanticPath>
      <BindingPath>SideScanSonarBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="navigationRadar" name="항해레이더 정보처리장치">
      <SemanticPath>NavigationRadarSemantic.xml</SemanticPath>
      <BindingPath>NavigationRadarBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="integratedNavigation" name="복합항법장치">
      <SemanticPath>IntegratedNavigationSemantic.xml</SemanticPath>
      <BindingPath>IntegratedNavigationBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="lidarProcessor" name="라이다 정보처리장치">
      <SemanticPath>LidarSemantic.xml</SemanticPath>
      <BindingPath>LidarBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="electroOptical" name="전자광학장치">
      <SemanticPath>ElectroOpticalSemantic.xml</SemanticPath>
      <BindingPath>ElectroOpticalBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="sensorFusion" name="센서융합 정보처리장치">
      <SemanticPath>SensorFusionSemantic.xml</SemanticPath>
      <BindingPath>SensorFusionBinding.xml</BindingPath>
    </SensorSpecRef>
    <!--<SensorSpecRef id="eots" name="전자광학장치" ref="./SensorSpec/ElectronicOpticalCamera.xml" />
        <SensorSpecRef id="camera" name="항해용카메라" ref="./SensorSpec/VoyageCamera.xml" />
        <SensorSpecRef id="radar" name="항해용레이더" ref="./SensorSpec/Radar.xml" />-->
    <SensorSpecRef id="navigationCamera" name="운항용카메라장치">
      <SemanticPath>NavigationCameraSemantic.xml</SemanticPath>
      <BindingPath>NavigationCameraBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="nearContactDetection" name="근거리접촉물탐지장치">
      <SemanticPath>NearContactDetectionSemantic.xml</SemanticPath>
      <BindingPath>NearContactDetectionBinding.xml</BindingPath>
    </SensorSpecRef>
    <SensorSpecRef id="electroOpticalProcessor" name="전자광학장치 영상처리 CSC">
      <SemanticPath>ElectroOpticalProcessorSemantic.xml</SemanticPath>
      <BindingPath>ElectroOpticalProcessorBinding.xml</BindingPath>
    </SensorSpecRef>
  </Sensors>
  <!-- Payload/임무장비 -->
  <Payloads>
    <PayloadSpecRef id="centralControl" name="중앙통제장치">
      <SemanticPath>CentralControlSemantic.xml</SemanticPath>
      <BindingPath>CentralControlBinding.xml</BindingPath>
    </PayloadSpecRef>
    <PayloadSpecRef id="remoteFireControl" name="원격사격통제장치">
      <SemanticPath>RemoteFireControlSemantic.xml</SemanticPath>
      <BindingPath>RemoteFireControlBinding.xml</BindingPath>
    </PayloadSpecRef>
  </Payloads>
  <!-- 플랫폼 장비 -->
  <Platform>
    <PlatformSpecRef id="platformController" name="선체제어장치">
      <SemanticPath>PlatformControllerSemantic.xml</SemanticPath>
      <BindingPath>PlatformControllerBinding.xml</BindingPath>
    </PlatformSpecRef>
    <PlatformSpecRef id="autonomousNavigation" name="자율운항장치">
      <SemanticPath>AutonomousNavigationSemantic.xml</SemanticPath>
      <BindingPath>AutonomousNavigationBinding.xml</BindingPath>
    </PlatformSpecRef>
  </Platform>
  <!-- 임무 장비 -->
  <!--
    <Payloads>
        <PayloadSpecRef id="missionController" name="임무통제장치" ref="./PayloadSpec/***.xml" />
        <PayloadSpecRef id="mainController" name="중앙통제장치" ref="./PayloadSpec/***.xml" />
        <PayloadSpecRef id="navalGun" name="함포" ref="./PayloadSpec/NavalGun.xml" />
        <PayloadSpecRef id="cis" name="복합감응소해장비" ref="./PayloadSpec/***.xml" />
        <PayloadSpecRef id="auvLauncher" name="AUV 진수장치" ref="./PayloadSpec/LARS.xml"/>
        <PayloadSpecRef id="auvRecovery" name="AUV 회수장치" ref="./PayloadSpec/***.xml"/>
        <PayloadSpecRef id="emdwLauncher" name="EMDW 진수장치" ref="./PayloadSpec/***.xml"/>
    </Payloads>

    -->
  <!-- 통신 장비 -->
  <Comms>
    <CommSpecRef id="networkAdapterDevice" name="네트워크추상화장치">
      <SemanticPath>NetworkAbstractionSemantic.xml</SemanticPath>
      <BindingPath>NetworkAbstractionBinding.xml</BindingPath>
    </CommSpecRef>
  </Comms>
</VehicleSpec>
