=== pepsimanpa/mcmc2/ProtocolXml/USV/SideScanSonar/CommonBindingSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://lignex1.com/mcmc2/umsSchema" xmlns="http://lignex1.com/mcmc2/umsSchema" elementFormDefault="qualified">
    <!-- AUV Reply 내장 Binding 확장 스키마 / 생성일시: 2026-08-04 11:51:54 KST -->
    <!-- 프로토콜 일반화 확장: ControlBinding/MonitorBinding 및 DDS/TCP/UDP/RS422 Channel 추가 / 2026-08-06 -->
    <xs:element name="SensorBinding" type="BindingCompositionType"/>
    <xs:element name="PlatformBinding" type="BindingCompositionType"/>
    <xs:element name="PayloadBinding" type="BindingCompositionType"/>
    <xs:element name="CommBinding" type="BindingCompositionType"/>
    <xs:complexType name="BindingCompositionType"><xs:sequence><xs:element name="Monitors" type="MonitorsType" minOccurs="0"/><xs:element name="Controls" type="ControlsType" minOccurs="0"/><xs:element name="SensorProducts" type="SensorProductsType" minOccurs="0"/></xs:sequence></xs:complexType>
    <xs:complexType name="MonitorsType"><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="MonitorBindingDDS" type="MonitorBindingDDSType"/><xs:element name="MonitorBinding" type="MonitorBindingType"/></xs:choice><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <xs:complexType name="ControlsType"><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="ControlBindingDDS" type="ControlBindingDDSType"/><xs:element name="ControlBinding" type="ControlBindingType"/></xs:choice><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <!-- 센서 산출물 Binding: Semantic SensorProductSpecs의 ProductStreamSpec과 실제 전송 Channel을 연결 -->
    <xs:complexType name="SensorProductsType"><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="ProductBinding" type="ProductBindingType"/></xs:choice><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <!-- 기존 DDS 전용 Binding XML 하위 호환용 Channel -->
    <xs:complexType name="ChannelType"><xs:attribute name="topicName" type="xs:string" use="required"/><xs:attribute name="typeName" type="xs:string" use="required"/></xs:complexType>
    <!-- 신규 프로토콜별 Channel -->
    <xs:complexType name="DDSChannelType"><xs:attribute name="topicName" type="xs:string" use="required"/><xs:attribute name="typeName" type="xs:string" use="required"/></xs:complexType>
    <xs:complexType name="MessageChannelType"><xs:attribute name="infoCode" type="xs:unsignedShort"/><xs:attribute name="messageType" type="xs:string" use="required"/></xs:complexType>
    <!-- RTP는 스트림 방식만 식별하며 IP/Port 등 통신 설정은 Binding 명세 범위에서 제외 -->
    <xs:complexType name="RTPChannelType"/>
    <xs:group name="ProtocolChannelChoice"><xs:choice><xs:element name="DDSChannel" type="DDSChannelType"/><xs:element name="TCPChannel" type="MessageChannelType"/><xs:element name="UDPChannel" type="MessageChannelType"/><xs:element name="RS422Channel" type="MessageChannelType"/><xs:element name="RTPChannel" type="RTPChannelType"/></xs:choice></xs:group>
    <xs:complexType name="FieldType"><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="cdm" type="xs:string"/><xs:attribute name="inputUnit" type="xs:string"/><xs:attribute name="outputUnit" type="xs:string"/><xs:attribute name="converter" type="xs:string"/></xs:complexType>
    <xs:complexType name="FixedFieldType"><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="cdm" type="xs:string"/><xs:attribute name="value" type="xs:string" use="required"/><xs:attribute name="converter" type="xs:string"/></xs:complexType>
    <xs:complexType name="DerivedFieldType"><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="cdm" type="xs:string"/><xs:attribute name="sourceField" type="xs:string"/><xs:attribute name="converter" type="xs:string"/></xs:complexType>
    <xs:complexType name="ElementType"><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:element name="Field" type="FieldType"/><xs:element name="FixedField" type="FixedFieldType"/><xs:element name="DerivedField" type="DerivedFieldType"/><xs:element name="ArrayField" type="ArrayFieldType"/></xs:choice><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="cdm" type="xs:string"/></xs:complexType>
    <xs:complexType name="ArrayFieldType"><xs:sequence><xs:element name="Element" type="ElementType"/></xs:sequence><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="cdm" type="xs:string"/><xs:attribute name="minOccurs" type="xs:nonNegativeInteger"/><xs:attribute name="maxOccurs" type="xs:string"/></xs:complexType>
    <xs:group name="BindingFieldChoice"><xs:choice><xs:element name="Field" type="FieldType"/><xs:element name="FixedField" type="FixedFieldType"/><xs:element name="DerivedField" type="DerivedFieldType"/><xs:element name="ArrayField" type="ArrayFieldType"/></xs:choice></xs:group>
    <xs:complexType name="MatchFieldType"><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute name="mask" type="xs:string" use="optional"/><xs:attribute name="value" type="xs:string" use="required"/></xs:complexType>
    <xs:complexType name="ProductBindingType"><xs:sequence><xs:group ref="ProtocolChannelChoice"/><xs:element name="MatchField" type="MatchFieldType" minOccurs="0"/></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <!-- 기존 DDS 전용 Binding 타입: 기존 XML 검증 호환을 위해 유지 -->
    <xs:complexType name="MonitorBindingDDSType"><xs:sequence><xs:element name="Channel" type="ChannelType"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <xs:complexType name="ReplyBindingType"><xs:sequence><xs:element name="Channel" type="ChannelType"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/><xs:attribute name="required" type="xs:boolean"/><xs:attribute name="timeout" type="xs:decimal"/></xs:complexType>
    <xs:complexType name="ControlBindingDDSType"><xs:sequence><xs:element name="Channel" type="ChannelType"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice><xs:element name="ReplyBinding" type="ReplyBindingType" minOccurs="0" maxOccurs="unbounded"/></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <!-- 신규 프로토콜 독립 Binding 타입 -->
    <xs:complexType name="MonitorBindingType"><xs:sequence><xs:group ref="ProtocolChannelChoice"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
    <xs:complexType name="ProtocolReplyBindingType"><xs:sequence><xs:group ref="ProtocolChannelChoice"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/><xs:attribute name="required" type="xs:boolean"/><xs:attribute name="timeout" type="xs:decimal"/></xs:complexType>
    <xs:complexType name="ControlBindingType"><xs:sequence><xs:group ref="ProtocolChannelChoice"/><xs:choice minOccurs="0" maxOccurs="unbounded"><xs:group ref="BindingFieldChoice"/></xs:choice><xs:element name="ReplyBinding" type="ProtocolReplyBindingType" minOccurs="0" maxOccurs="unbounded"/></xs:sequence><xs:attribute name="semantic_id" type="xs:string" use="required"/></xs:complexType>
</xs:schema>

=== pepsimanpa/mcmc2/ProtocolXml/USV/NavigationRadar/NavigationRadarBinding.xml
<?xml version='1.0' encoding='UTF-8'?>
<SensorBinding xmlns="http://lignex1.com/mcmc2/umsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lignex1.com/mcmc2/umsSchema ../../XSD/CommonBindingSchema.xsd">
  <!--항해레이더 정보처리장치 Binding: 항해레이더 정보처리 CSC 및 원격통제장치 CSCI 기준-->
  <!--공용 식별자 규칙: SurfaceDetection=0x03, NavRadarProcessorCard=0x03, 별도 세부 장비 ID 없음 → System.Target.NavigationRadar는 0x03/0x03/0x00 DestinationType을 준비한다.-->
  <!--생성 USVMessageBase/DestinationType/commandID는 OM/Adapter가 준비하고 Binding은 물리 wire 표현만 선언한다.-->
  <Monitors semantic_id="monitor">
        <MonitorBinding semantic_id="radarContacts">
      <DDSChannel topicName="RUSV::SA::CIPE::RadarContactReportType" typeName="RadarContactReportType"/>
      <Field name="usvHeader"/>
      <Field name="contactNum" cdm="Contact.Radar.Count" dataType="Int32"/>
      <ArrayField name="contactTypeList" cdm="Contact.Radar.List" minOccurs="0" maxOccurs="256">
        <Element name="contact" cdm="Contact.Radar.Item">
          <Field name="contactID" cdm="Contact.Identifier" dataType="Int32"/>
          <Field name="detectionRange" cdm="Contact.Range" dataType="Float32"/>
          <Field name="azimuth" cdm="Contact.Azimuth" dataType="Float32"/>
          <Field name="latitude" cdm="Contact.Position.Latitude" dataType="Float64"/>
          <Field name="longitude" cdm="Contact.Position.Longitude" dataType="Float64"/>
          <Field name="course" cdm="Contact.Course" dataType="Float32"/>
          <Field name="speed" cdm="Contact.Speed" dataType="Float32"/>
          <Field name="size" cdm="Contact.Size" dataType="Float32"/>
          <Field name="rcs" cdm="Contact.RCS" dataType="Float32"/>
          <Field name="cpa" cdm="Contact.CPA" dataType="Float32"/>
          <Field name="tcpa" cdm="Contact.TCPA" dataType="Float32"/>
          <Field name="collisionRisk" cdm="Contact.CollisionRisk" dataType="Float32"/>
        </Element>
      </ArrayField>
    </MonitorBinding>
        <MonitorBinding semantic_id="aisContacts">
      <!--AISContactType 수치 Range는 공용 구조체 원본 정합성 확인 전까지 Binding converter/validation을 두지 않는다.-->
      <DDSChannel topicName="RUSV::SA::CIPE::AISContactReportType" typeName="AISContactReportType"/>
      <!--AISContactType 일부 Range/Unavailable 셀의 열 정합성이 불명확하므로 타입/길이만 직접 반영하고 의미 보정은 하지 않는다.-->
      <Field name="usvHeader"/>
      <Field name="contactNum" cdm="Contact.AIS.Count" dataType="Int32"/>
      <ArrayField name="contactTypeList" cdm="Contact.AIS.List" minOccurs="0" maxOccurs="256">
        <Element name="contact" cdm="Contact.AIS.Item">
          <Field name="contactID" cdm="Contact.Identifier" dataType="Int32"/>
          <Field name="mmsi" cdm="Contact.AIS.MMSI" dataType="UInt32"/>
          <Field name="latitude" cdm="Contact.Position.Latitude" dataType="Float64"/>
          <Field name="longitude" cdm="Contact.Position.Longitude" dataType="Float64"/>
          <Field name="course" cdm="Contact.Course" dataType="Float32"/>
          <Field name="speed" cdm="Contact.Speed" dataType="Float32"/>
          <Field name="detectionRange" cdm="Contact.Range" dataType="Float32"/>
          <Field name="cpa" cdm="Contact.CPA" dataType="Float32"/>
          <Field name="tcpa" cdm="Contact.TCPA" dataType="Float32"/>
          <Field name="collisionRisk" cdm="Contact.CollisionRisk" dataType="Float32"/>
          <Field name="heading" cdm="Contact.Heading" dataType="Float32"/>
          <Field name="rateOfTurn" cdm="Contact.RateOfTurn" dataType="Float32"/>
          <Field name="shipName" cdm="Contact.AIS.ShipName" dataType="UInt8" length="21" format="string"/>
          <Field name="shipType" cdm="Contact.AIS.ShipType" dataType="UInt32"/>
          <Field name="shipLength" cdm="Contact.Length" dataType="Int32"/>
          <Field name="shipWidth" cdm="Contact.Width" dataType="Int32"/>
        </Element>
      </ArrayField>
    </MonitorBinding>
        <MonitorBinding semantic_id="radarStatus">
      <DDSChannel topicName="RUSV::SA::CIPE::RadarAISStatusReportType" typeName="RadarAISStatusReportType"/>
      <!--radarMessageTransmitStatus의 구체적인 '레이더 메시지' 대상은 원문에서 미확정.-->
      <Field name="usvHeader"/>
      <Field name="radarTransmitStatus" cdm="Radar.Status.Transmit" dataType="UInt8">
        <ValueMap>
          <Map cdm="Radar.Transmit.Standby" value="0"/>
          <Map cdm="Radar.Transmit.Transmit" value="1"/>
        </ValueMap>
      </Field>
      <Field name="radarRange" cdm="Radar.Status.Range" dataType="Int32"/>
      <Field name="radarMessageTransmitStatus" cdm="Radar.Status.MessageTransmit" dataType="UInt8">
        <ValueMap>
          <Map cdm="MessageOutput.Stop" value="0"/>
          <Map cdm="MessageOutput.Output" value="1"/>
        </ValueMap>
      </Field>
    </MonitorBinding>
        <MonitorBinding semantic_id="radarVideoStatus">
      <DDSChannel topicName="RUSV::SA::CIPE::RadarAISStatusReportType" typeName="RadarAISStatusReportType"/>
      <Field name="usvHeader"/>
      <Field name="videoBroadcastStatus" cdm="Radar.Video.BroadcastStatus" dataType="UInt8">
        <ValueMap>
          <Map cdm="Streaming.Stop" value="0"/>
          <Map cdm="Streaming.Transmit" value="1"/>
        </ValueMap>
      </Field>
      <!--frameWidth/frameHeight는 항해레이더 정보처리 CSC에서 long(4 Byte)로 확인되어 Int32로 선언한다.-->
      <Field name="frameWidth" cdm="Radar.Video.Frame.Width" dataType="Int32"/>
      <Field name="frameHeight" cdm="Radar.Video.Frame.Height" dataType="Int32"/>
    </MonitorBinding>
        <MonitorBinding semantic_id="aisStatus">
      <DDSChannel topicName="RUSV::SA::CIPE::RadarAISStatusReportType" typeName="RadarAISStatusReportType"/>
      <Field name="usvHeader"/>
      <Field name="aisMessageTransmitStatus" cdm="AIS.Status.MessageTransmit" dataType="UInt8">
        <ValueMap>
          <Map cdm="MessageOutput.Standby" value="0"/>
          <Map cdm="MessageOutput.Transmit" value="1"/>
        </ValueMap>
      </Field>
      <Field name="aisRange" cdm="AIS.Status.Range" dataType="Int32"/>
    </MonitorBinding>
        <MonitorBinding semantic_id="cipeCbitStatus">
      <DDSChannel topicName="RUSV::SO::CIPE::CIPECBITReportType" typeName="CIPECBITReportType"/>
      <Field name="usvHeader"/>
      <Field name="cipeCBITStatus.cipeOperationalStatus" cdm="Health.CIPE.EquipmentLink" dataType="UInt8">
        <ValueMap>
          <Map cdm="Health.CIPE.Radar.Connected" value="10"/>
          <Map cdm="Health.CIPE.Radar.Disconnected" value="13"/>
          <Map cdm="Health.CIPE.Lidar.Connected" value="20"/>
          <Map cdm="Health.CIPE.Lidar.Disconnected" value="23"/>
          <Map cdm="Health.CIPE.NearContact.Connected" value="30"/>
          <Map cdm="Health.CIPE.NearContact.Disconnected" value="33"/>
          <Map cdm="Health.CIPE.EOIR.Connected" value="40"/>
          <Map cdm="Health.CIPE.EOIR.Disconnected" value="43"/>
        </ValueMap>
      </Field>
      <Field name="cipeCBITStatus.operationalStatus" cdm="Health.CIPE.OperationalStatus" dataType="UInt8">
        <ValueMap>
          <Map cdm="Health.Normal" value="0"/>
          <Map cdm="Health.Degraded" value="1"/>
          <Map cdm="Health.Unavailable" value="2"/>
          <Map cdm="Health.NoResponse" value="3"/>
        </ValueMap>
      </Field>
    </MonitorBinding>
  </Monitors>
  <Controls semantic_id="control">
        <ControlBinding semantic_id="startIntegration">
      <!--DestinationType: dstEquipmentType=0x03(SurfaceDetection), dstEquipmentID=0x03(NavRadarProcessorCard).-->
      <DDSChannel topicName="RUSV::C2::RCU::IntegrationControlType" typeName="IntegrationControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="destination" sourceField="System.Target.NavigationRadar"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <ReplyBinding semantic_id="startIntegrationAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
    </ControlBinding>
        <ControlBinding semantic_id="restartSystem">
      <!--DestinationType: dstEquipmentType=0x03(SurfaceDetection), dstEquipmentID=0x03(NavRadarProcessorCard).-->
      <DDSChannel topicName="RUSV::C2::RCU::SystemRebootControlType" typeName="SystemRebootControlType"/>
      <DerivedField name="usvHeader" sourceField="System.Generated.USVMessageBase"/>
      <DerivedField name="destination" sourceField="System.Target.NavigationRadar"/>
      <DerivedField name="commandID" sourceField="System.Generated.CommandSequence" dataType="UInt16"/>
      <ReplyBinding semantic_id="restartSystemAck" required="true">
        <DDSChannel topicName="RUSV::C2::CIPE::CommandStatusReportType" typeName="CommandStatusReportType"/>
        <Field name="usvHeader"/>
        <Field name="commandStatusReport.dstEquipmentType" cdm="Control.Response.Destination.EquipmentType" dataType="UInt8"/>
        <Field name="commandStatusReport.dstEquipmentID" cdm="Control.Response.Destination.EquipmentID" dataType="UInt8"/>
        <Field name="commandStatusReport.status" cdm="Control.Response.Status" dataType="UInt8"/>
        <Field name="commandID" cdm="Message.Correlation.NumericID" dataType="UInt16"/>
      </ReplyBinding>
    </ControlBinding>
        <ControlBinding semantic_id="requestIbit">
      <!--DestinationType: dstEquipmentType=0x03(SurfaceDetection), dstEquipmentID=0x03(NavRadarProcessorCard).-->
